let currentURL = "";
const docsFrame = document.getElementById("docs-frame");
const chatWindow = document.getElementById("chat-window");
const ws = new WebSocket("ws://localhost:8765");

function mcp(tool, args) {
  return new Promise((resolve, reject) => {
    const request = { tool, args };
    ws.send(JSON.stringify(request));
    
    const listener = (e) => {
      try {
        const data = JSON.parse(e.data);
        if (data.error) reject(data.error);
        else resolve(data);
      } catch (err) { reject(err); } 
      finally { ws.removeEventListener("message", listener); }
    };
    ws.addEventListener("message", listener);
  });
}

document.getElementById("load-btn").onclick = async (e) => {
  e.preventDefault();
  currentURL = document.getElementById("url-input").value.trim();
  if (!currentURL) return;

  appendMsg(`Loading: ${currentURL}`);
  
  // 1. CLEAR THE IFRAME IMMEDIATELY
  docsFrame.src = "about:blank"; 
  
  try {
    await mcp("crawl_page", { url: currentURL });
    appendMsg("Indexed ✓ (full docs site)");
    
    // 2. FORCE RELOAD WITH TIMESTAMP
    // slightly different timestamp to ensure it's unique
    docsFrame.src = "mirror.html?v=" + Date.now(); 
  } catch (err) {
    appendMsg("❌ Error during indexing");
    console.error(err);
  }
};

document.getElementById("ask-btn").onclick = async (event) => {
  event.preventDefault(); 
  const q = document.getElementById("question-input").value.trim();
  if (!q) return;

  appendMsg(`You: ${q}`);

  try {
    const res = await mcp("query_page_tool", { url: currentURL, question: q });
    
    // 1. Show the text answer
    appendMsg(`JumpBot: ${res.answer}`);
    
    // 2. Load the PRE-HIGHLIGHTED file generated by Python
    if (res.highlight_file) {
        // Add timestamp to force reload (fix caching)
        const cacheBuster = new Date().getTime();
        // Ensure path is correct relative to index.html
        docsFrame.src = `${res.highlight_file}?v=${cacheBuster}`;
    }
    
  } catch (err) {
    appendMsg("❌ Error querying JumpBot");
    console.error(err);
  }
};

function injectHighlightStyle() {
    try {
        const doc = docsFrame.contentDocument;
        if (!doc || doc.getElementById("jumpbot-style")) return;
        const style = doc.createElement("style");
        style.id = "jumpbot-style";
        style.textContent = `.jumpbot-highlight { background-color: #ffeb3b !important; color: black !important; font-weight: bold; }`;
        doc.head.appendChild(style);
    } catch (e) { console.log("CORS Error"); }
}

function highlightTextInIframe(searchText) {
    const win = docsFrame.contentWindow;
    const doc = docsFrame.contentDocument;
    if (!win || !doc) return;
    win.getSelection().removeAllRanges();
    const found = win.find(searchText, false, false, true, false, true, false);
    if (found) {
        try {
            const range = win.getSelection().getRangeAt(0);
            const span = doc.createElement("span");
            span.classList.add("jumpbot-highlight");
            range.surroundContents(span);
        } catch (e) { console.log("Highlight error", e); }
    }
}

function appendMsg(msg) {
  chatWindow.innerHTML += `<div>${msg}</div>`;
  chatWindow.scrollTop = chatWindow.scrollHeight;
}
window.mcp = mcp;